### ISSUE TITLE
Fatal - ds down

### ISSUE THREAD

**Issue by Coronell** [ProximoSrl/Jarvis.Framework#24]
```
    "ex" : {
        "me" : "Collection was modified; enumeration operation may not execute.",
        "sr" : "mscorlib",
        "st" : "   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at Jarvis.Framework.Kernel.ProjectionEngine.ProjectionEngine.Poll()
   at Jarvis.Framework.Kernel.ProjectionEngine.ProjectionEngine.Update()
   at Jarvis.DocumentStore.Core.EvenstoreHooks.TriggerProjectionEngineHook.PostCommit(ICommit committed) in c:\\agents\\build\\work\\16f8c173489d5d09\\src\\Jarvis.DocumentStore.Core\\EvenstoreHooks\\TriggerProjectionEngineHook.cs:line 30
   at NEventStore.OptimisticEventStore.Commit(CommitAttempt attempt)
   at NEventStore.OptimisticEventStream.PersistChanges(Guid commitId)
   at NEventStore.OptimisticEventStream.CommitChanges(Guid commitId)
   at Jarvis.NEventStoreEx.CommonDomainEx.Persistence.EventStore.AbstractRepository.Save(String bucketId, IAggregateEx aggregate, Guid commitId, Action`1 updateHeaders)
   at Jarvis.NEventStoreEx.CommonDomainEx.Persistence.EventStore.RepositoryEx.Save(IAggregateEx aggregate, Guid commitId, Action`1 updateHeaders)
   at Jarvis.NEventStoreEx.CommonDomainEx.Persistence.EventStore.CachableAggregateCachedRepository`1.Save(Guid commitId, Action`1 updateHeaders)
   at Jarvis.Framework.Kernel.Commands.RepositoryCommandHandler`2.FindAndModify(EventStoreIdentity id, Action`1 callback, Boolean createIfNotExists)
   at Jarvis.DocumentStore.Core.CommandHandlers.DocumentDescriptorHandlers.CreateDocumentDescriptorCommandHandler.Execute(CreateDocumentDescriptor cmd) in c:\\agents\\build\\work\\16f8c173489d5d09\\src\\Jarvis.DocumentStore.Core\\CommandHandlers\\DocumentDescriptorHandlers\\CreateDocumentDescriptorCommandHandler.cs:line 9
   at Jarvis.Framework.Kernel.Commands.AbstractCommandHandler`1.Handle(TCommand cmd)
   at Jarvis.Framework.Kernel.Commands.RepositoryCommandHandler`2.Handle(TCommand cmd)
   at Jarvis.Framework.Kernel.Commands.AbstractCommandHandler`1.Handle(ICommand command)
   at Jarvis.Framework.Kernel.Commands.InProcessCommandBus.Handle(ICommandHandler handler, ICommand command)
   at Jarvis.Framework.Kernel.Commands.InProcessCommandBus.SendLocal(ICommand command, String impersonatingUser)
   at Jarvis.Framework.Kernel.Commands.InProcessCommandBus.Send(ICommand command, String impersonatingUser)
   at Jarvis.DocumentStore.Core.EventHandlers.DocumentWorkflow.On(DocumentDescriptorInitialized e) in c:\\agents\\build\\work\\16f8c173489d5d09\\src\\Jarvis.DocumentStore.Core\\EventHandlers\\DocumentWorkflow.cs:line 130
   at invoke(Object , Object[] )
   at Jarvis.Framework.Kernel.Events.AbstractProjection.Handle(IDomainEvent e, Boolean isReplay)
   at Jarvis.Framework.Kernel.ProjectionEngine.ProjectionEngine.DispatchCommit(ICommit commit, String slotName, Int64 startCheckpoint)"
    },

```

**Comment by alkampfergit** [comment]
ok

**Comment by andreabalducci** [comment]
issue is on _clients enumeration, probably the Poll() call is executed while ProjectionEngine is starting.
Actions:
[] transform _clients to array from List<>
[] ignore poll requests on uninitialized projection engine

**Comment by alkampfergit** [comment]
The error could occur also when projection engine is stopping and another thread issue a poll.
